### PR TITLE
Redesign

### PR DESCRIPTION
**Pull request by cyberblast**
Declaration of individual autonomy and independence.
Manifestation of responsibilities.

### CODE REVIEW

**Comment by whardeman** [comment]
I like the change and its intent, but after much thought I also agree with concerns raised by @pandabear41 and @torin555.  For those of you who have played Victoria or Crusader Kings strategy games. you know about _casus belli_, which is essentially needed justification for war, and in those games, having a valid _casus belli_ may require a lot of work. There's no limit to what can be considered a valid reason for war in Screeps. I think the problem here is that there will be some people who want to go to war with OCS, but don't want to be seen as the aggressors (for fear of riling other alliances). If we hand them a _casus belli_ by virtue of one member's actions, we've just excused their war against OCS.

I'm abstaining from this vote. Whatever the group at large decides, I'll accept. I just want to help people consider this in light of the "law of unintended consequences."

**Comment by karlthepagan** [comment]
A stronger defensive pact (i.e. "an attack on one is an attack on all") requires a firm military commitment which I do not believe that all members will adhere to.

I think the ambassador should be responsible for communicating this to other alliances.

**Comment by whardeman** [comment]
@karlthepagan Agreed on all points. This is the impasse we have... members cannot be counted on to defend each other and outside alliances can't be counted on to respect our nuanced approach to player independence.

**Comment by cyberblast** [comment]
Well, looking back at the few wars we had, I really think it doesn't make a big difference. 
Most players don't need an explicit "casus belli" as this is a territory game. And pure existence at the wrong place is reason enough. 

On the other side there are some (also some big, old) players who do care about politics and stuff. At least to some extend. Those people will understand and respect this, our statement. 

And there is another side of it: It gives a lot of more freedom to each of us. 
Regarding this freedom, I share all of the concerns, as it may lead to misuse or rude behavior. 
Which could have an effect on all of us again. 

On the other side, some members already left, because of our restrictive rules. Or this "join or die" rule (which was never intended to be interpreted like that, but obviously is). 

Now THIS PR will flush all of this. 

Whats the alternative? 

I'm not sure. Maybe we can reduce concerns about this change. 
We could add some rules to prohibit rude behaviour or misuse of membership. 
We should also forge some military alliances on top of our alliance. 
Please discuss those additions internally (at [137](https://github.com/cyberblast/screeps.ocs.internal/issues/137) or a new issue)

**Comment by TafThorne** [comment]
If we are a full alliance then the constitution must become more restrictive to the members.  That would have to include punishment for those who disobey and trigger wars or whatever.  

There is a clear and continuing sentiment that this is not an alliance and does not plan on having a centralised military strategy.  That fact has to be publicised to other entities and our public constitution is one way of clearly doing that.  Our diplomats can also immediately state "they acted alone, if you flatten them it will not be treated as aggression to us" if the OCS member was the aggressor.  

> because it's written in our constitution that member's actions don't reflect on the alliance, doesn't mean any other alliances or players will care

There are not dozens of alliances in this game.  It will not take that long for the message to get around.  Our diplomats could even contact each other alliance individually to make them aware of the change or clarification of policy.  In politics nothing can guarantee the other side doing whatever they want.  Even a statement of "an attack one one, is an attack on us all" would be little help.  

> A stronger defensive pact (i.e. "an attack on one is an attack on all") requires a firm military commitment which I do not believe that all members will adhere to.

Indeed.  The new constitution makes it easier for us to be both a member of the OCS and some other military organisation.  This could be another alliance or some kind of area based pact.  I would be able to promise that I could take military action against an agressor of my ally in the new system.  In the old one I would need permission from OCS.

**Comment by torin555** [comment]
@cyberblast Those are fair points, although I think there are many players who do play this in similar ways to Paradox strategy games and would actually use an attack by a member as a reason to attack other members. I think the most common example of that would be a player declaring war on the whole alliance until the member that attacked them was removed from the alliance. That's just an opinion based on messages I've seen in the past, and it might not matter.

I agree completely that the join or die rule at the very least should be removed. I've had a few people who have asked if we plan to wipe them out if they don't join after reading the constitution, and it does make it more challenging to recruit.

At the very least I think we should retain the rule against attacking members of OCS. We don't want people in the alliance to abuse their spot in the whitelist just to attack our members.

**Comment by Dasku** [comment]
I think these are examples of why we need an Ambassador or closer ties with the wider screeps community and alliances. I'd hope in the future, if anything happened between players, they could speak to our ambassador about it before declaring wars etc. This obviously may not always be the case, and like many people have said we cannot control what other alliances or players do. But we can try and build relationships with the big/main ones to prevent incidents getting out of hand in the future.

**Comment by cyberblast** [comment]
> At the very least I think we should retain the rule against attacking members of OCS. We don't want people in the alliance to abuse their spot in the whitelist just to attack our members. 

Uhm yes. But I think it's obvious and common sense that it's not ok to attack people within the alliance. But we can still discuss this. For now, I'll be merging :)

**Pull request merged**
